#!/bin/sh
#
# delete_roster 
#
# usage: delete_roster

DOMAIN=india.sun.com
# ldap server configuration
LDAP_HOST=usg180.india.sun.com
LDAP_PORT=389
BASE_DN="dc=india,dc=sun,dc=com"
LDAP_BINDDN="cn=Directory Manager"
LDAP_BINDPW="netscape"

#UID_RANGES="1500001 1605000 1705000 1805000" 
UID_RANGES="1600000" 

RANGE_LIM=18000

for urange in $UID_RANGES ;
do
   # create ldif file
   ldif="/tmp/del-rosters-$urange.ldif" 
   rm -f $ldif
   touch $ldif
   cur=0
   uid=$urange

   while [ "$cur" -lt $RANGE_LIM ]
   do
     echo "dn: uid=${uid},ou=people,o=india.sun.com,${BASE_DN}" >> $ldif
     echo "changetype: modify" >> $ldif
     echo "delete: sunIMUserRoster" >> $ldif
     echo >> $ldif
   
     cur=`expr $cur + 1`
     uid=`expr $uid + 1`

   done

   /usr/bin/ldapmodify -c -p ${LDAP_PORT} -h ${LDAP_HOST} -D "${LDAP_BINDDN}" -w "${LDAP_BINDPW}" -f ${ldif}
   echo "done with $urange"

done

exit $?
