#!/bin/sh
#
# create_test_users 
# create test user for IM functional tests
#
# usage: create_test_users <test_env>

. $1


ldif=/tmp/soimdel.ldif
rm -f $ldif
touch $ldif

cur=0
uid=1500000
while [ "$cur" -lt 5000 ]
do
  echo "dn: uid=${uid},ou=people,${BASE_DN}" >> $ldif
  echo "changetype: delete" >> $ldif
  echo >> $ldif

  cur=`expr $cur + 1`
  uid=`expr $uid + 1`

done

cur=0
uid=1600000
while [ "$cur" -lt 5000 ]
do
  echo "dn: uid=${uid},ou=people,${BASE_DN}" >> $ldif
  echo "changetype: delete" >> $ldif
  echo >> $ldif

  cur=`expr $cur + 1`
  uid=`expr $uid + 1`

done

# load the LDIF file
/usr/bin/ldapmodify -c -p ${LDAP_PORT} -h ${LDAP_HOST} -D "${LDAP_BINDDN}" -w "${LDAP_BINDPW}" -f ${ldif}


exit $?

