#!/bin/sh
# start shell

CLIENTJARS=/export/home/stress/client
classpath=$CLIENTJARS/imservice.jar:$CLIENTJARS/jso.jar:$CLIENTJARS/log4j.jar:$CLIENTJARS/jaxen-core.jar:$CLIENTJARS/saxpath.jar:$CLIENTJARS/xp.jar
#jargs="-Xmx1024m" 
/usr/bin/java -cp $classpath com.sun.im.service.shells.MultiShell -factory com.sun.im.service.xmpp.XMPPSessionProvider
