# This Brewfile will install all your specified packages.
# It's a Ruby file, which is why the syntax looks this way.

tap "hashicorp/tap"
tap "fluxcd/tap"

# --- CLI Tools (Formulae) ---
brew "npm"
brew "docker"
brew "docker-buildx"
brew "gitleaks"
brew "just"
brew "kind"
brew "helm"
brew "kubectl"
brew "yq"
brew "awscli"
brew "pre-commit"
brew "asdf"
brew "direnv"
brew "parallel"
brew "fluxcd/tap/flux"
brew "hashicorp/tap/vault"
brew "gh"
brew "jq"
brew "wget"
brew "zsh"
brew "zsh-completions"
brew "tmux"
brew "git"
brew "htop"
brew "npm"
brew "k9s"
brew "stern"
brew "kubecolor"
cask "numi"
cask "lens"
cask "beekeeper-studio"
cask "appcleaner"
brew "maven"
cask "the-unarchiver"
brew "lazydocker"
brew "cloudflared"
brew "openjdk"
brew "uv"
brew "node"
cask "gcloud-cli"
cask 'iterm2'
cask 'notion'
cask 'visual-studio-code'
brew "fnm"
brew "bun"
brew "witr"
