#!/bin/sh
ADMIN=/tmp/rm_pkgadmin
echo "action=nocheck" > $ADMIN
echo "idepend=nocheck" >> $ADMIN
echo "rdepend=nocheck" >> $ADMIN
echo "space=nocheck" >> $ADMIN
echo "mail=" >> $ADMIN

/usr/sbin/mpsadmserver unconfigure -nodisplay
/usr/sbin/mpsadmserver uninstall

echo "Uconfiguration is done for Directory server."

echo "Removing the configuration for Directory Server."

/usr/sbin/directoryserver -u 5.2 unconfigure -nodisplay
/usr/sbin/directoryserver uninstall

echo "Unconfiguration is done for Admin Server"


for i in `ps -eaf |grep -i SUNWps |awk '{ print $2 }'`; do kill -9 $i; done

for i in `ps -eaf |grep -i ant |awk '{ print $2 }'`; do kill -9 $i; done

for i in `ps -eaf |grep -i SUNWportal |awk '{ print $2 }'`; do kill -9 $i; done

for i in `ps -eaf |grep -i SUNWam |awk '{ print $2 }'`; do kill -9 $i; done

for i in `ps -eaf |grep -i imq |awk '{ print $2 }'`; do kill -9 $i; done

for i in `ps -eaf |grep -i appservd |awk '{ print $2 }'`; do kill -9 $i; done

for i in `ps -eaf |grep -i webservd |awk '{ print $2 }'`; do kill -9 $i; done

for i in `ps -eaf |grep -i entsys |awk '{ print $2 }'`; do kill -9 $i; done

for i in `ps -eaf |grep -i jdk |awk '{ print $2 }'`; do kill -9 $i; done

for i in `ps -eaf |grep -i java |awk '{ print $2 }'`; do kill -9 $i; done

for i in `ps -eaf |grep -i Mulitplexor |awk '{ print $2 }'`; do kill -9 $i; done 

for i in `ps -eaf |grep -i ldap |awk '{ print $2 }'`; do kill -9 $i; done

for i in `ps -eaf |grep -i slapd |awk '{ print $2 }'`; do kill -9 $i; done

for i in `ps -eaf |grep -i icsuser |awk '{ print $2 }'`; do kill -9 $i; done

for i in `ps -eaf |grep -i httpd |awk '{ print $2 }'`; do kill -9 $i; done

for i in `ps -eaf |grep -i imsched |awk '{ print $2 }'`; do kill -9 $i; done
for i in `ps -eaf |grep -i imapd |awk '{ print $2 }'`; do kill -9 $i; done
for i in `ps -eaf |grep -i tcp_smtp_server |awk '{ print $2 }'`; do kill -9 $i; done
for i in `ps -eaf |grep -i popd |awk '{ print $2 }'`; do kill -9 $i; done
for i in `ps -eaf |grep -i dispatcher |awk '{ print $2 }'`; do kill -9 $i; done
for i in `ps -eaf |grep -i stored |awk '{ print $2 }'`; do kill -9 $i; done
for i in `ps -eaf |grep -i jobcontroller |awk '{ print $2 }'`; do kill -9 $i; done
for i in `ps -eaf |grep -i enpd |awk '{ print $2 }'`; do kill -9 $i; done
for i in `ps -eaf |grep -i watcher |awk '{ print $2 }'`; do kill -9 $i; done


#COMMCLI
pkgrm -A -n -a $ADMIN  SUNWcomic
pkgrm -A -n -a $ADMIN  SUNWcomis

pkgrm -A -n -a $ADMIN  SUNWaclg
pkgrm -A -n -a $ADMIN  SUNWamcds

# Access Manager
pkgrm -A -n -a $ADMIN  SUNWamcon
pkgrm -A -n -a $ADMIN  SUNWamdoc
pkgrm -A -n -a $ADMIN  SUNWamdistauth
pkgrm -A -n -a $ADMIN  SUNWamdsc
pkgrm -A -n -a $ADMIN  SUNWamext
pkgrm -A -n -a $ADMIN  SUNWamfcd
pkgrm -A -n -a $ADMIN  SUNWamrsa
pkgrm -A -n -a $ADMIN  SUNWamsac
pkgrm -A -n -a $ADMIN  SUNWamsai
pkgrm -A -n -a $ADMIN  SUNWamsam
pkgrm -A -n -a $ADMIN  SUNWamsas
pkgrm -A -n -a $ADMIN  SUNWamsci
pkgrm -A -n -a $ADMIN  SUNWamsdk
pkgrm -A -n -a $ADMIN  SUNWamsvc
pkgrm -A -n -a $ADMIN  SUNWamfm
pkgrm -A -n -a $ADMIN  SUNWamsws
pkgrm -A -n -a $ADMIN  SUNWamutl
pkgrm -A -n -a $ADMIN  SUNWamwlc
pkgrm -A -n -a $ADMIN  SUNWamwli
pkgrm -A -n -a $ADMIN  SUNWamwls
pkgrm -A -n -a $ADMIN  SUNWamws
pkgrm -A -n -a $ADMIN  SUNWamwsc
pkgrm -A -n -a $ADMIN  SUNWamwsi
pkgrm -A -n -a $ADMIN  SUNWamwss
pkgrm -A -n -a $ADMIN  SUNWamsdkconfig
pkgrm -A -n -a $ADMIN  SUNWamsvcconfig
pkgrm -A -n -a $ADMIN  SUNWammae
pkgrm -A -n -a $ADMIN SUNWamma
pkgrm -A -n -a $ADMIN  SUNWamclnt
pkgrm -A -n -a $ADMIN  SUNWamsfodb
pkgrm -A -n -a $ADMIN  SUNWcomds
pkgrm -A -n -a $ADMIN  SUNWampwd


pkgrm -A -n -a $ADMIN  SUNWasha
pkgrm -A -n -a $ADMIN  SUNWasvc
pkgrm -A -n -a $ADMIN  SUNWasvcp
pkgrm -A -n -a $ADMIN  SUNWasvu
pkgrm -A -n -a $ADMIN  SUNWdsha
pkgrm -A -n -a $ADMIN  SUNWdsvcp
pkgrm -A -n -a $ADMIN  SUNWdsvh
pkgrm -A -n -a $ADMIN  SUNWdsvhx
pkgrm -A -n -a $ADMIN  SUNWdsvpl
pkgrm -A -n -a $ADMIN  SUNWdsvr
pkgrm -A -n -a $ADMIN  SUNWdsvmn
pkgrm -A -n -a $ADMIN  SUNWasvmn

pkgrm -A -n -a $ADMIN  SUNWdsvu
pkgrm -A -n -a $ADMIN  SUNWdsvx
pkgrm -A -n -a $ADMIN  SUNWjaf
pkgrm -A -n -a $ADMIN  SUNWjato
pkgrm -A -n -a $ADMIN  SUNWjatodoc
pkgrm -A -n -a $ADMIN  SUNWjatodmo
pkgrm -A -n -a $ADMIN  SUNWjaxp
pkgrm -A -n -a $ADMIN  SUNWjaxb
pkgrm -A -n -a $ADMIN  SUNWjaxws
pkgrm -A -n -a $ADMIN  SUNWjmail
pkgrm -A -n -a $ADMIN  SUNWldk
pkgrm -A -n -a $ADMIN  SUNWldjk
pkgrm -A -n -a $ADMIN  SUNWldkx
pkgrm -A -n -a $ADMIN  SUNWljdk
pkgrm -A -n -a $ADMIN  SUNWant
pkgrm -A -n -a $ADMIN  SUNWsoar-server
pkgrm -A -n -a $ADMIN  SUNWsoar-sdk

if [ `uname -r` != "5.10" ]; then
  pkgrm -A -n -a $ADMIN  SUNWpr
  pkgrm -A -n -a $ADMIN  SUNWprx
  pkgrm -A -n -a $ADMIN  SUNWprd
  pkgrm -A -n -a $ADMIN  SUNWtls
  pkgrm -A -n -a $ADMIN  SUNWtlsu
  pkgrm -A -n -a $ADMIN  SUNWtlsx
  pkgrm -A -n -a $ADMIN  SUNWjss
  pkgrm -A -n -a $ADMIN  SUNWjssx
  pkgrm -A -n -a $ADMIN  SUNWicu
  pkgrm -A -n -a $ADMIN  SUNWicux
  pkgrm -A -n -a $ADMIN  SUNWicud
  pkgrm -A -n -a $ADMIN  SUNWsaslx
  pkgrm -A -n -a $ADMIN  SUNWsasl
  pkgrm -A -n -a $ADMIN SUNWmctag
  pkgrm -A -n -a $ADMIN SUNWmcosx
  pkgrm -A -n -a $ADMIN SUNWmcos
  pkgrm -A -n -a $ADMIN SUNWmconr
  pkgrm -A -n -a $ADMIN SUNWmcon
  pkgrm -A -n -a $ADMIN SUNWtcatu
fi

pkgrm -A -n -a $ADMIN  SUNWxrpcrt
pkgrm -A -n -a $ADMIN  SUNWxsrt
pkgrm -A -n -a $ADMIN  SUNWxrgrt
pkgrm -A -n -a $ADMIN  SUNWwscl
pkgrm -A -n -a $ADMIN  SUNWOrionUninstaller
pkgrm -A -n -a $ADMIN  SUNWwbsvr
pkgrm -A -n -a $ADMIN  SUNWawbsvr
pkgrm -A -n -a $ADMIN SUNWebnfs
pkgrm -A -n -a $ADMIN SUNWiimps
pkgrm -A -n -a $ADMIN SUNWiimgw
pkgrm -A -n -a $ADMIN SUNWcomms 
pkgrm -A -n -a $ADMIN SUNWentsys5u1i
pkgrm -A -n -a $ADMIN SUNWiimdv
pkgrm -A -n -a $ADMIN SUNWpsap

pkgrm -A -n -a $ADMIN SUNWjdmk-runtime-jmx
pkgrm -A -n -a $ADMIN SUNWjdmk-runtime
pkgrm -A -n -a $ADMIN SUNWjhrt
pkgrm -A -n -a $ADMIN SUNWderby-core
pkgrm -A -n -a $ADMIN SUNWcacao
pkgrm -A -n -a $ADMIN SUNWcacaocfg
pkgrm -A -n -a $ADMIN SUNWcacaomon
pkgrm -A -n -a $ADMIN SUNWderby-javadoc-dev

#IM
pkgrm -A -n -a $ADMIN SUNWiim
pkgrm -A -n -a $ADMIN SUNWiimc
pkgrm -A -n -a $ADMIN SUNWiimd
pkgrm -A -n -a $ADMIN SUNWiimid
pkgrm -A -n -a $ADMIN SUNWiimin
pkgrm -A -n -a $ADMIN SUNWiimjd
pkgrm -A -n -a $ADMIN SUNWiimm

#UWC
pkgrm -A -n -a $ADMIN SUNWuwc

#PORTAL

pkgrm -A -n -a $ADMIN SUNWps
pkgrm -A -n -a $ADMIN SUNWpsa
pkgrm -A -n -a $ADMIN SUNWpsc
pkgrm -A -n -a $ADMIN SUNWpscfg
pkgrm -A -n -a $ADMIN SUNWpscp
pkgrm -A -n -a $ADMIN SUNWpsdis
pkgrm -A -n -a $ADMIN SUNWpsdt
pkgrm -A -n -a $ADMIN SUNWpsdta
pkgrm -A -n -a $ADMIN SUNWpsdtc
pkgrm -A -n -a $ADMIN SUNWpsdtm
pkgrm -A -n -a $ADMIN SUNWpsdtp
pkgrm -A -n -a $ADMIN SUNWpsdtx
pkgrm -A -n -a $ADMIN SUNWpsgw
pkgrm -A -n -a $ADMIN SUNWpsgwa
pkgrm -A -n -a $ADMIN SUNWpsgwm
pkgrm -A -n -a $ADMIN SUNWpsgws
pkgrm -A -n -a $ADMIN SUNWpsks
pkgrm -A -n -a $ADMIN SUNWpsmig
pkgrm -A -n -a $ADMIN SUNWpsmp
pkgrm -A -n -a $ADMIN SUNWpsma
pkgrm -A -n -a $ADMIN SUNWpsmad
pkgrm -A -n -a $ADMIN SUNWpsmai
pkgrm -A -n -a $ADMIN SUNWpsmas
pkgrm -A -n -a $ADMIN SUNWpsnf
pkgrm -A -n -a $ADMIN SUNWpsnl
pkgrm -A -n -a $ADMIN SUNWpsnlp
pkgrm -A -n -a $ADMIN SUNWpsnm
pkgrm -A -n -a $ADMIN SUNWpsoh
pkgrm -A -n -a $ADMIN SUNWpsp
pkgrm -A -n -a $ADMIN SUNWpsplt
pkgrm -A -n -a $ADMIN SUNWpspltconfig
pkgrm -A -n -a $ADMIN SUNWpsps
pkgrm -A -n -a $ADMIN SUNWpsrw
pkgrm -A -n -a $ADMIN SUNWpsrwa
pkgrm -A -n -a $ADMIN SUNWpsrwp
pkgrm -A -n -a $ADMIN SUNWpssdk
pkgrm -A -n -a $ADMIN SUNWpsse
pkgrm -A -n -a $ADMIN SUNWpssea
pkgrm -A -n -a $ADMIN SUNWpssep
pkgrm -A -n -a $ADMIN SUNWpssp
pkgrm -A -n -a $ADMIN SUNWpsss
pkgrm -A -n -a $ADMIN SUNWpssso
pkgrm -A -n -a $ADMIN SUNWpsssoa
pkgrm -A -n -a $ADMIN SUNWpssub
pkgrm -A -n -a $ADMIN SUNWpstlj
pkgrm -A -n -a $ADMIN SUNWpswp
pkgrm -A -n -a $ADMIN SUNWpswsrpcommon
pkgrm -A -n -a $ADMIN SUNWpswsrpconsumer
pkgrm -A -n -a $ADMIN SUNWpswsrpconsumerconfig
pkgrm -A -n -a $ADMIN SUNWpswsrpconsumersample
pkgrm -A -n -a $ADMIN SUNWpswsrpproducer
pkgrm -A -n -a $ADMIN SUNWpswsrpproducersample
pkgrm -A -n -a $ADMIN SUNWportal-admin
pkgrm -A -n -a $ADMIN SUNWportal-base
pkgrm -A -n -a $ADMIN SUNWportal-portlets
pkgrm -A -n -a $ADMIN SUNWportal-search
pkgrm -A -n -a $ADMIN SUNWportal-sracommon
pkgrm -A -n -a $ADMIN SUNWportal-sracore
pkgrm -A -n -a $ADMIN SUNWportal-sragateway
pkgrm -A -n -a $ADMIN SUNWportal-sranetletproxy
pkgrm -A -n -a $ADMIN SUNWportal-srarewriterproxy
pkgrm -A -n -a $ADMIN SUNWiqjx
pkgrm -A -n -a $ADMIN SUNWiqcdv
pkgrm -A -n -a $ADMIN SUNWiqcrt
pkgrm -A -n -a $ADMIN SUNWiqdzh
pkgrm -A -n -a $ADMIN SUNWiqcde
pkgrm -A -n -a $ADMIN SUNWiqces
pkgrm -A -n -a $ADMIN SUNWiqcfr
pkgrm -A -n -a $ADMIN SUNWiqcja
pkgrm -A -n -a $ADMIN SUNWiqcko
pkgrm -A -n -a $ADMIN SUNWiqctw
pkgrm -A -n -a $ADMIN SUNWiqczh
pkgrm -A -n -a $ADMIN SUNWiqdja
pkgrm -A -n -a $ADMIN SUNWiqdoc
pkgrm -A -n -a $ADMIN SUNWiqdz
pkgrm -A -n -a $ADMIN SUNWiqfs
pkgrm -A -n -a $ADMIN SUNWiqide
pkgrm -A -n -a $ADMIN SUNWiqies
pkgrm -A -n -a $ADMIN SUNWiqifr
pkgrm -A -n -a $ADMIN SUNWiqija
pkgrm -A -n -a $ADMIN SUNWiqiko
pkgrm -A -n -a $ADMIN SUNWiqitw
pkgrm -A -n -a $ADMIN SUNWiqizh
pkgrm -A -n -a $ADMIN SUNWiqjx
pkgrm -A -n -a $ADMIN SUNWiqlen
pkgrm -A -n -a $ADMIN SUNWiqlpl
pkgrm -A -n -a $ADMIN SUNWiqr
pkgrm -A -n -a $ADMIN SUNWiqu
pkgrm -A -n -a $ADMIN SUNWiquc
pkgrm -A -n -a $ADMIN SUNWiqum
pkgrm -A -n -a $ADMIN SUNWamjwsdp
pkgrm -A -n -a $ADMIN SUNWamconsdk
pkgrm -A -n -a $ADMIN SUNWmsgco
pkgrm -A -n -a $ADMIN SUNWmessaging-server-64
pkgrm -A -n -a $ADMIN SUNWmessaging-server
pkgrm -A -n -a $ADMIN SUNWmsgen
pkgrm -A -n -a $ADMIN SUNWmsgin
pkgrm -A -n -a $ADMIN SUNWmsglb
pkgrm -A -n -a $ADMIN SUNWmsgmf
pkgrm -A -n -a $ADMIN SUNWmsgmp
pkgrm -A -n -a $ADMIN SUNWmsgmt
pkgrm -A -n -a $ADMIN SUNWmsgst
pkgrm -A -n -a $ADMIN SUNWmsgwm
pkgrm -A -n -a $ADMIN SUNWasvc
pkgrm -A -n -a $ADMIN SUNWasvcp
pkgrm -A -n -a $ADMIN SUNWasvr
pkgrm -A -n -a $ADMIN SUNWasvu
pkgrm -A -n -a $ADMIN SUNWrewrt

#CALENDAR

pkgrm -A -n -a $ADMIN SUNWica5
pkgrm -A -n -a $ADMIN SUNWics5

#DPS
pkgrm -A -n -a $ADMIN SUNWdps
pkgrm -A -n -a $ADMIN SUNWdpsg
pkgrm -A -n -a $ADMIN SUNWdpsi

#MAP
pkgrm -A -n -a $ADMIN SUNWma
pkgrm -A -n -a $ADMIN SUNWmae

#Application Server
pkgrm -A -n -a $ADMIN SUNWaswbcr
pkgrm -A -n -a $ADMIN SUNWasut
pkgrm -A -n -a $ADMIN SUNWasuee
pkgrm -A -n -a $ADMIN SUNWast
pkgrm -A -n -a $ADMIN SUNWasmanee
pkgrm -A -n -a $ADMIN SUNWasman
pkgrm -A -n -a $ADMIN SUNWasjdoc
pkgrm -A -n -a $ADMIN SUNWasdemdb
pkgrm -A -n -a $ADMIN SUNWasdem
pkgrm -A -n -a $ADMIN SUNWasu
pkgrm -A -n -a $ADMIN SUNWashdm
pkgrm -A -n -a $ADMIN SUNWashdemdb
pkgrm -A -n -a $ADMIN SUNWashdem
pkgrm -A -n -a $ADMIN SUNWasdb
pkgrm -A -n -a $ADMIN SUNWascmnse
pkgrm -A -n -a $ADMIN SUNWascmn
pkgrm -A -n -a $ADMIN SUNWascml
pkgrm -A -n -a $ADMIN SUNWasacee
pkgrm -A -n -a $ADMIN SUNWasac
pkgrm -A -n -a $ADMIN SUNWasJdbcDrivers
pkgrm -A -n -a $ADMIN SUNWaslb
pkgrm -A -n -a $ADMIN SUNWasr

#HADB
pkgrm -A -n -a $ADMIN SUNWhadbx
pkgrm -A -n -a $ADMIN SUNWhadbs
pkgrm -A -n -a $ADMIN SUNWhadbm
pkgrm -A -n -a $ADMIN SUNWhadbj
pkgrm -A -n -a $ADMIN SUNWhadbc
pkgrm -A -n -a $ADMIN SUNWhadba

#Sleepycat DB
pkgrm -A -n -a $ADMIN SUNWbdb
pkgrm -A -n -a $ADMIN SUNWbdbj


#JavaHelp
pkgrm -A -n -a $ADMIN SUNWjhdem
pkgrm -A -n -a $ADMIN SUNWjhdev
pkgrm -A -n -a $ADMIN SUNWjhdoc
pkgrm -A -n -a $ADMIN SUNWjhrt


#Java
pkgrm -A -n -a $ADMIN SUNWj5dvx
pkgrm -A -n -a $ADMIN SUNWj5rtx
pkgrm -A -n -a $ADMIN SUNWj5man
pkgrm -A -n -a $ADMIN SUNWj5jmp
pkgrm -A -n -a $ADMIN SUNWj5dmx
pkgrm -A -n -a $ADMIN SUNWj5dmo
pkgrm -A -n -a $ADMIN SUNWj5cfg
pkgrm -A -n -a $ADMIN SUNWj5dev
pkgrm -A -n -a $ADMIN SUNWj5rt
if [ -f /var/sadm/prod/entsys/uninstall_Sun_Java_tm__Enterprise_System_2004Q2.class ]; then
	pkgrm -A -n -a $ADMIN SUNWj3dvx
	pkgrm -A -n -a $ADMIN SUNWj3rtx
	pkgrm -A -n -a $ADMIN SUNWj3man
	pkgrm -A -n -a $ADMIN SUNWj3jmp
	pkgrm -A -n -a $ADMIN SUNWj3dmo
	pkgrm -A -n -a $ADMIN SUNWj3cfg
	pkgrm -A -n -a $ADMIN SUNWj3dev
	pkgrm -A -n -a $ADMIN SUNWj3rt
fi
pkgrm -A -n -a $ADMIN SUNWentsys-uninstall
pkgrm -A -n -a $ADMIN SUNWentsys4
pkgrm -A -n -a $ADMIN SUNWentsysl10n-uninstall
pkgrm -A -n -a $ADMIN SUNWentsys4-uninstall-l10n
pkgrm -A -n -a $ADMIN SUNWps-entsys4
pkgrm -A -n -a $ADMIN SUNWps7_0-entsys
pkgrm -A -n -a $ADMIN SUNWps7_0-entsys-l10n
pkgrm -A -n -a $ADMIN SUNWentsys4


#JES5
pkgrm -A -n -a $ADMIN SUNWasvmn
pkgrm -A -n -a $ADMIN SUNWasvr
pkgrm -A -n -a $ADMIN SUNWldap-directory
pkgrm -A -n -a $ADMIN SUNWldap-directory-client
pkgrm -A -n -a $ADMIN SUNWldap-directory-config
pkgrm -A -n -a $ADMIN SUNWldap-directory-dev
pkgrm -A -n -a $ADMIN SUNWldap-directory-man
pkgrm -A -n -a $ADMIN SUNWldap-shared
pkgrm -A -n -a $ADMIN SUNWentsys5
pkgrm -A -n -a $ADMIN SUNWentsys5i
pkgrm -A -n -a $ADMIN SUNWamdistauth
pkgrm -A -n -a $ADMIN SUNWproxy
pkgrm -A -n -a $ADMIN SUNWsrvc-registry-deploy
pkgrm -A -n -a $ADMIN SUNWsrvc-registry-dev
pkgrm -A -n -a $ADMIN SUNWcacaort
pkgrm -A -n -a $ADMIN SUNWcacaowsvr
pkgrm -A -n -a $ADMIN SUNWderby-usr
pkgrm -A -n -a $ADMIN SUNWexplj
pkgrm -A -n -a $ADMIN SUNWfastinfoset
pkgrm -A -n -a $ADMIN SUNWhabdi
pkgrm -A -n -a $ADMIN SUNWhadbv
pkgrm -A -n -a $ADMIN SUNWjstl
pkgrm -A -n -a $ADMIN SUNWldapcsdk-dev
pkgrm -A -n -a $ADMIN SUNWldapcsdk-libs
pkgrm -A -n -a $ADMIN SUNWldapcsdk-tools
pkgrm -A -n -a $ADMIN SUNWmfwk-man
pkgrm -A -n -a $ADMIN SUNWmfwk-rt
pkgrm -A -n -a $ADMIN SUNWxwss
pkgrm -A -n -a $ADMIN SUNWwbsvr7
pkgrm -A -n -a $ADMIN SUNWwbsvr7-cli
pkgrm -A -n -a $ADMIN SUNWwbsvr7-dev
pkgrm -A -n -a $ADMIN SUNWwbsvr7x
pkgrm -A -n -a $ADMIN  SUNWamfm
pkgrm -A -n -a $ADMIN  SUNWldap-console-agent
pkgrm -A -n -a $ADMIN  SUNWldap-console-cli
pkgrm -A -n -a $ADMIN  SUNWldap-console-common
pkgrm -A -n -a $ADMIN  SUNWldap-console-gui
pkgrm -A -n -a $ADMIN  SUNWldap-console-gui-help
pkgrm -A -n -a $ADMIN  SUNWldap-console-gui-help-l10n
pkgrm -A -n -a $ADMIN  SUNWldap-console-gui-l10n
pkgrm -A -n -a $ADMIN  SUNWldap-console-var
pkgrm -A -n -a $ADMIN  SUNWldap-directory-client-l10n
pkgrm -A -n -a $ADMIN  SUNWldap-directory-l10n
pkgrm -A -n -a $ADMIN  SUNWldap-shared-l10n
pkgrm -A -n -a $ADMIN  SUNWsaml2
pkgrm -A -n -a $ADMIN SUNWderby-usr 
pkgrm -A -n -a $ADMIN SUNWebnfs
pkgrm -A -n -a $ADMIN SUNWhadbe
pkgrm -A -n -a $ADMIN SUNWhadbi
pkgrm -A -n -a $ADMIN SUNWpslcfg
pkgrm -A -n -a $ADMIN SUNWiwc
pkgrm -A -n -a $ADMIN SUNWj6cfg
pkgrm -A -n -a $ADMIN SUNWj6dev
pkgrm -A -n -a $ADMIN SUNWj6dvx
pkgrm -A -n -a $ADMIN SUNWj6rt
pkgrm -A -n -a $ADMIN SUNWj6rtx
pkgrm -A -n -a $ADMIN SUNWldap-proxy
pkgrm -A -n -a $ADMIN SUNWldap-proxy-client
pkgrm -A -n -a $ADMIN SUNWldap-proxy-client-l10n
pkgrm -A -n -a $ADMIN SUNWldap-proxy-l10n
pkgrm -A -n -a $ADMIN SUNWldap-proxy-man
pkgrm -A -n -a $ADMIN SUNWma-l10n
pkgrm -A -n -a $ADMIN SUNWwbsvr7-cli-l10n
pkgrm -A -n -a $ADMIN SUNWwbsvr7-l10n
pkgrm -A -n -a $ADMIN SUNWentsys5u1
pkgrm -A -n -a $ADMIN SUNWam-l10n
pkgrm -A -n -a $ADMIN SUNWamclnt-l10n
pkgrm -A -n -a $ADMIN SUNWamdistauth-l10n
pkgrm -A -n -a $ADMIN SUNWamma-l10n
pkgrm -A -n -a $ADMIN SUNWentsys5u1i
pkgrm -A -n -a $ADMIN SUNWcommda
pkgrm -A -n -a $ADMIN SUNWdavserver
pkgrm -A -n -a $ADMIN SUNWjavadb-core
pkgrm -A -n -a $ADMIN SUNWjavadb-demo 
pkgrm -A -n -a $ADMIN SUNWjavadb-derby2javadblnk
pkgrm -A -n -a $ADMIN SUNWjavadb-docs
pkgrm -A -n -a $ADMIN SUNWjavadb-javadoc-dev
pkgrm -A -n -a $ADMIN SUNWjavadb-usr
pkgrm -A -n -a $ADMIN SUNWiimsc


#${SCRIPT_HOME}/kill ns-slapd

rm -rf /opt/SUNWcomds
rm -rf /space/SUNWcomds
rm -rf /opt/SUNWasvmn
rm -rf /opt/SUNWdsvmn
rm -rf /var/opt/SUNWpsdefault
rm -rf /etc/opt/SUNWiim
rm -rf /var/opt/SUNWcomm
rm -rf /opt/CS /opt/MS /opt/IM /opt/SUNWcomm /opt/SUNWuwc
rm -rf /space/CS /space/MS /space/IM /space/SUNWcomm /space/SUNWuwc
rm -rf /opt/SUNWmfwk
rm -rf /opt/SUNWmlib
rm -rf /opt/SUNWits
rm -rf /usr/share/lib/Derby
rm -rf /etc/opt/SUNWmfwk
rm -rf /var/opt/SUNWmfwk
rm -rf /usr/share/bdb/db.jar
rm -rf /opt/SUNWam
rm -rf /opt/SUNWcomds
rm -rf /opt/SUNWasvmn
rm -rf /opt/SUNWcomm
rm -rf /opt/SUNWdsvmn
rm -rf /opt/SUNWps
rm -rf /opt/SUNWiim
rm -rf /opt/SUNWappserver7
rm -rf /opt/SUNWappserver
rm -rf /opt/SUNWwbsvr
rm -rf /opt/locale
rm -rf /var/opt/mps
rm -rf /usr/sunone/servers
rm -rf /usr/jdk
rm -rf /var/sadm/prod/*
rm -rf /var/sadm/prod/orion
rm -rf /var/opt/SUNWappserver7
rm -rf /var/opt/SUNWappserver
rm -rf /var/opt/SUNWps
rm -rf /var/opt/SUNWam
rm -rf /var/opt/SUNWiim
rm -rf /etc/opt/SUNWps
rm -rf /etc/opt/SUNWappserver7
rm -rf /etc/opt/SUNWappserver
rm -rf /etc/opt/SUNWam
rm -rf /etc/opt/SUNWiim
rm -rf /etc/opt/SUNWma
rm -rf /opt/SUNWma
rm -rf /etc/ds/v5.2
rm -rf /usr/ds/v5.2
rm -rf /am_*
rm -rf /opt/ws
rm -rf /opt/as
rm -rf /opt/as_var
rm -rf /opt/ds
rm -rf /jes*
rm -rf /opt/SUNWportal
rm -rf /etc/opt/SUNWportal
rm -rf /var/opt/SUNWportal
rm -rf /opt/SUNWcacao
rm -rf /etc/opt/SUNWcacao
rm -rf /var/opt/SUNWcacao
rm -rf /space/PS 
rm -rf /space/AM
rm -rf /space/IS
rm -rf /space/DS 
rm -rf /space/AS 
rm -rf /space/WS 
rm -rf /space/RS
rm -rf /etc/cacao
rm -rf /usr/lib/cacao
rm -rf /var/cacao
rm -rf /opt/SUNWwbsvr7
rm -rf /var/opt/SUNWwbsvr7
rm -rf /opt/sun
rm -rf /var/opt/sun
rm -rf /var/opt/webconsole
rm -rf /var/opt/mps/serverroot
rm -rf /etc/mps/admin
rm -rf /var/opt/SUNWhadb



echo "Removing .lock and .pkg files and Logs and Productregistry"

rm -rf  /var/sadm/install/.pkg.lock
rm -rf  /var/sadm/install/.lockfile
rm -rf  /var/sadm/install/productregistry
rm -rf  /var/sadm/install/logs/*

echo "Removing files from /var/sadm/prod"
rm -rf  /var/sadm/prod/*
