#!/usr/bin/perl
use Expect;
$user=$ARGV[0];
$domain=$ARGV[1];
$host=$ARGV[2];
$timeout=3;
$cmd = "./GenerateUserCert.sh $user $domain $host";
$exp = new Expect();
$exp->raw_pty(1);
$exp->debug($debug);
$exp->spawn($cmd);
$exp->expect($timeout,'-re', ':\s$');
$exp->send ("\n");
$exp->expect($timeout,'-re', ':\s$');
$exp->send ("\n");
$exp->expect($timeout,'-re', ':\s$');
$exp->send ("\n");
$exp->expect($timeout,'-re', ':\s$');
$exp->send ("\n");
$exp->expect($timeout,'-re', ':\s$');
$exp->send ("\n");
$exp->expect($timeout,'-re', ':\s$');
$exp->send ("$user\@$domain\n");
$exp->expect($timeout,'-re', ':\s$');
$exp->send ("$user\@$domain\n");
$exp->expect($timeout,'-re', ':\s$');
$exp->send ("$pwd\n");
$exp->expect($timeout,'-re', ':\s$');
$exp->send ("\n");
$exp->expect($timeout,'-re', ':\s$');
$exp->send ("$pwd\n");
$exp->expect($timeout,'-re', ':\s$');
$exp->send ("y\n");
$exp->expect($timeout,'-re', ':\s$');
$exp->send ("y\n");
$exp->expect($timeout,'-re', ':\s$');
$exp->send ("$pwd\n");
$exp->expect($timeout,'-re', ':\s$');
$exp->send ("$pwd\n");
$exp->expect($timeout,'-re', 'p12\s$');
$exp->soft_close();
exit;
