#!/usr/bin/bash
msg_pkg=`pkginfo |grep SUNWmessaging |cut -f2 -d" "`
msg_dir=`pkginfo -l $msg_pkg|grep BASEDIR |cut -f2 -d":"`
cd $msg_dir/sbin
configutil -o service.pop.enablesslport -v yes
configutil -o service.pop.sslport -v 995
configutil -o service.pop.sslusessl -v 1
configutil -o service.imap.enablesslport -v yes
configutil -o service.imap.sslport -v 993
configutil -o service.imap.sslusessl -v yes
configutil -o service.http.enablesslport -v yes
configutil -o service.http.sslusessl -v yes
configutil -o service.http.sslport -v 8991

#LDAP_SSL based configuration
configutil -o local.service.pab.ldapport -v 636
configutil -o local.ugldapport -v 636
configutil -o local.ugldapusessl -v yes
configutil -o local.service.pab.ldapusessl -v yes
configutil -o local.ldapcheckcert -v 0

sed -e 's/!TLS_PORT=465/TLS_PORT=465/' ../config/dispatcher.cnf > ../config/t;
mv ../config/t ../config/dispatcher.cnf;
./msgcert generate-certDB

echo "Want to enable SMIME?(Y/N):"

read config_option

if [ "$config_option" == "Y" ]
then
        configutil -o local.webmail.smime.enable -v yes
        configutil -o local.webmail.cert.enable -v yes
fi
