#!/bin/ksh
#LD_LIBRARY_PATH=$PWD/app
#export LD_LIBRARY_PATH
#COREFILE=core_mail-gw2_tcp_smtp_server_40780_2504_1192114033_26613
COREFILE=65695493_pkg_app_tcp_smtp_server.core
export COREFILE
if [[ ! -n $COREFILE ]]
  then
  print -u2 "The name of the corefile has not been defined."
  print -u2 "Edit the opencore script & append the name of the"
  print -u2 "corefile to the \"COREFILE=\" command"
  exit 22
fi
dbx -s dbxrc
