authentication:
  host : 10.101.217.183
  port : 443
  uri : /oauth/token
  username: admin
  password: netwitness
  secure: true

tests:
  - name: Get all preferences per user
    output-filename: test.txt
    socket:
      host: 10.101.217.122
      uri: /response/socket
      port: 443
      secure: true
    error-uri: /user/queue/global/error
    apis:

      - send:
          uri: /ws/administration/global/get/user/preferences
          payload:
             id: "req-1"
             stream:
               limit: 20
               batch: 5
        subscriptions:
          - uri: /user/queue/administration/global/get/user/preferences
        reference:
          code: 0
          data:
            contextMenuEnabled: true
            dateFormat: MM/dd/yyyy
            defaultComponentUrl: "/unified"
            notificationEnabled: true
            spacingType: LOOSE
            themeType: DARK
            timeFormat: HR12
            timeZone: UTC
            userLocale: en_US
          request:
            data:
            id: req-1

subscriptions:
  channels:
    - "/user/queue/incidents/new"
    - "/user/queue/incidents/in_progress"
    - "/some/channel"
    - "/some/other/channel"

requests:
  # Requests for landing page
  requestsList:
    -
      channel: /ws/response/incidents
      message: "{
                    \"id\": \"req-01\",
                    \"page\": null,
                    \"stream\": {
                        \"limit\": 1
                    },
                    \"sort\": [{
                        \"field\": \"prioritySort\",
                        \"descending\": true
                    }],
                    \"filter\": [{
                        \"field\": \"statusSort\",
                        \"value\": 0,
                        \"values\": null,
                        \"range\": null,
                        \"isNull\": false
                    }]
                }"

out:
  file: "/tmp/test.txt"
