if &term != 'xterm' 
  set term=linux 
endif 
syntax on 
set nocompatible 
set hlsearch 
set ic
"set columns=120 
"set lines=80 
highlight Normal     ctermfg=LightGrey  ctermbg=Black 
highlight Search     ctermfg=0          ctermbg=7       cterm=NONE 
highlight Visual                                        cterm=reverse 
highlight Cursor     ctermfg=Black      ctermbg=Green   cterm=bold 
highlight Special    ctermfg=Brown 
highlight Comment    ctermfg=Blue 
highlight StatusLine ctermfg=blue       ctermbg=white 
highlight Statement  ctermfg=Yellow                     cterm=NONE 
highlight Type                                          cterm=NONE
